### ISSUE TITLE
Adicionar validacao para o campo 'slug'

### ISSUE THREAD

**Issue by brizental** [SPURB/gestaourbanasp#5]
Principalmente, retirar espacos em branco, acentos e caracteres especiais do geral.

Para os eventos, tentar fazer com que o slug seja criado automaticamente, quando o titulo for preenchido.

**Comment by tchaguitos** [comment]
Hey, @brizental, será que resolve? https://github.com/SPURB/gestaourbanasp/pull/11

Existem outros lugares? Só achei eventos e categorias.

**Comment by brizental** [comment]
@tchaguitos Obrigada pela contribuição! Faz tempo que na mexo nesse projeto, mas vou dar uma olha essa semana na PR!

**Comment by tchaguitos** [comment]
@brizental hey, tranquilo! eu acabei caindo por acaso no repositório e vi umas issues abertas, aí resolvi mandar PR uadhfifaafjdd :)
